# Generated by Django 4.1.4 on 2022-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMiniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
